language: android
jdk:
    - oraclejdk7
env:
  matrix:
    - ANDROID_TARGET=android-23 ANDROID_ABI=armeabi-v7a
android:
  components:
    - tools
    - platform-tools
    - build-tools-23.0.1
    - android-23
    - extra-android-m2repository
    - extra-android-support
before_script:
    - chmod +x ./gradlew