language: android
jdk:
    - oraclejdk8
env:
  matrix:
    - ANDROID_TARGET=android-23 ANDROID_ABI=armeabi-v7a
  global:
    - ADB_INSTALL_TIMEOUT=8
android:
  components:
    - tools
    - platform-tools
    - build-tools-23.0.2
    - android-23
    - extra-android-m2repository
    - extra-android-support